kerio.lib.translation = {
	"wlibLoginPage": {
		"%1 %2 and %3":"%1 %2 і %3",
		"%1 %2 to %3":"від %1 %2 до %3",
		"%1 is supported only from version %2":"%1 підтримується лише з версії %2",
		"%1 is supported only to version %2":"%1 підтримується лише до версії %2",
		"%1Confirm the certificate%2 for an automated login to other Kerio applications.":"%1Підтвердіть сертифікат%2 для автоматичного входу в інші програми Kerio.",
		"2FA Code":"Код 2FA",
		"Access denied by administrator.":"Доступ заборонено адміністратором.",
		"Continue anyway":"Продовжити все одно",
		"For the best user experience please use Google Chrome.":"Для найкращого користувацького досвіду використовуйте Google Chrome.",
		"Incorrect username or password":"Невірне ім'я користувача або пароль",
		"Integration with Linux":"Інтеграція з Linux",
		"Integration with Mac":"Інтеграція з Mac",
		"Integration with Windows":"Інтеграція з Windows",
		"Integration with device":"Інтеграція з пристроєм",
		"Internal problem while sending recovery email. Please contact admin.":"Внутрішня проблема під час відправлення листа для відновлення. Будь ласка, зверніться до адміністратора.",
		"Keep me logged in":"Запам'ятати мене",
		"Login":"Увійти",
		"Password":"Пароль",
		"Please enter 2FA Code using Google or Microsoft Authenticator Apps":"Будь ласка, введіть код 2FA за допомогою додатків Google або Microsoft Authenticator",
		"Please login again.":"Будь ласка, увійдіть знову.",
		"Please use PC or Mac.":"Використовуйте PC або Mac.",
		"Please use one of the supported browsers:":"Використовуйте один із підтримуваних браузерів:",
		"Please use the recommended resolution of %1x%2 or higher.":"Рекомендується використовувати роздільну здатність %1x%2 або вище.",
		"Please wait for $val$ seconds before your next attempt.":"Будь ласка, зачекайте $val$ секунд перед наступною спробою.",
		"Recovery Email":"Електронна пошта для відновлення",
		"Recovery Email (not your account email)":"Електронна пошта для відновлення (не електронна пошта вашого облікового запису)",
		"Recovery code sent. Please check your email.":"Код відновлення відправлено. Будь ласка, перевірте свою електронну пошту.",
		"Recovery email not set for your account. Recovery code not sent. Please contact admin.":"Електронна пошта для відновлення не встановлена для вашого облікового запису. Код відновлення не відправлено. Будь ласка, зверніться до адміністратора.",
		"Submit 2FA Code":"Відправити код 2FA",
		"Supported browsers:":"Підтримувані браузери:",
		"The functionality is very limited. Using PC or Mac is recommended instead.":"Функціональність дуже обмежена. Замість цього рекомендується використовувати PC або Mac.",
		"Username":"Ім'я користувача",
		"Wrong 2FA code. Please try again. If error persists, contact your administrator (attempt: $val$)":"Невірний код 2FA. Будь ласка, спробуйте ще раз. Якщо помилка повторюється, зверніться до адміністратора (спроба: $val$)",
		"Wrong 2FA code. Please try again. If error persists, contact your administrator.":"Невірний код 2FA. Будь ласка, спробуйте ще раз. Якщо помилка повторюється, зверніться до вашого адміністратора.",
		"Your %1 browser is not supported":"Ваш браузер %1 не підтримується",
		"Your browser is blocked.":"Ваш браузер заблоковано.",
		"Your browser or its version is not supported.":"Застосовуваний браузер або його версія не підтримується.",
		"Your device is not supported.":"Використовуваний пристрій не підтримується.",
		"Your display resolution is too low.":"Роздільна здатність екрана занадто низька.",
		"Your session has expired.":"Час сеансу вичерпано.",
		"and newer":"і новіші"
    }
};